# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cache_samc_cpp <- function(kernel, resistance, fidelity, absorbtion, symmetric) {
    .Call('_LSTDConnect_cache_samc', PACKAGE = 'LSTDConnect', kernel, resistance, fidelity, absorbtion, symmetric)
}

samc_print_cache_as_matrix <- function(ca) {
    invisible(.Call('_LSTDConnect_samc_print_cache_as_matrix', PACKAGE = 'LSTDConnect', ca))
}

samc_cache_sizes_cpp <- function(ca) {
    .Call('_LSTDConnect_samc_cache_sizes', PACKAGE = 'LSTDConnect', ca)
}

samc_step_cpp <- function(steps, ca, pop_in, dead_in) {
    .Call('_LSTDConnect_samc_step', PACKAGE = 'LSTDConnect', steps, ca, pop_in, dead_in)
}

